// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/er_mark.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9107242456221639524),
    name: 'ErMark',
    lastPropertyId: const obx_int.IdUid(8, 8750566117250950896),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1242407081622902188),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6298168001450453680),
        name: 'date',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(1, 2648259274619208320),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4440961941601994762),
        name: 'shift',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 1100823987542823409),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2378873535396146673),
        name: 'caseType',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 2784491969690038386),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6847488618662874106),
        name: 'patientName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1584877198907618881),
        name: 'ageYears',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3863469336149467927),
        name: 'remarks',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8750566117250950896),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1632380097378122196),
    name: 'Investigation',
    lastPropertyId: const obx_int.IdUid(3, 2217868057989587760),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 112321924687017534),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3578113801953495654),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2217868057989587760),
        name: 'price',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 1632380097378122196),
    lastIndexId: const obx_int.IdUid(3, 2784491969690038386),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ErMark: obx_int.EntityDefinition<ErMark>(
      model: _entities[0],
      toOneRelations: (ErMark object) => [],
      toManyRelations: (ErMark object) => {},
      getId: (ErMark object) => object.id,
      setId: (ErMark object, int id) {
        object.id = id;
      },
      objectToFB: (ErMark object, fb.Builder fbb) {
        final patientNameOffset = fbb.writeString(object.patientName);
        final remarksOffset = fbb.writeString(object.remarks);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addInt64(2, object.shift);
        fbb.addInt64(3, object.caseType);
        fbb.addOffset(4, patientNameOffset);
        fbb.addInt64(5, object.ageYears);
        fbb.addOffset(6, remarksOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ErMark()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
          )
          ..shift = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..caseType = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..patientName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..ageYears = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..remarks = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ErMark] entity fields to define ObjectBox queries.
class ErMark_ {
  /// See [ErMark.id].
  static final id = obx.QueryIntegerProperty<ErMark>(
    _entities[0].properties[0],
  );

  /// See [ErMark.date].
  static final date = obx.QueryDateProperty<ErMark>(_entities[0].properties[1]);

  /// See [ErMark.shift].
  static final shift = obx.QueryIntegerProperty<ErMark>(
    _entities[0].properties[2],
  );

  /// See [ErMark.caseType].
  static final caseType = obx.QueryIntegerProperty<ErMark>(
    _entities[0].properties[3],
  );

  /// See [ErMark.patientName].
  static final patientName = obx.QueryStringProperty<ErMark>(
    _entities[0].properties[4],
  );

  /// See [ErMark.ageYears].
  static final ageYears = obx.QueryIntegerProperty<ErMark>(
    _entities[0].properties[5],
  );

  /// See [ErMark.remarks].
  static final remarks = obx.QueryStringProperty<ErMark>(
    _entities[0].properties[6],
  );

  /// See [ErMark.createdAt].
  static final createdAt = obx.QueryDateProperty<ErMark>(
    _entities[0].properties[7],
  );
}
